name: API Build
 
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering if needed
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: myazureacr.azurecr.io
          username: myazureacr
          password: XPqucsyoO7XMJJWAjy5l9WRqYBtBu36W7weOhlYd0M+ACRDpemgw
 
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: myazureacr.azurecr.io/dummy:latest
          file: ./Dockerfile
          context: .
